[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "linear-diophantine"
version = "0.1"
dependencies = [
    "numpy",
    "hsnf",
    "pytest",
    "pytest-cov"
]

[tool.pytest.ini_options]
pythonpath = "./lineardiophantine"
