name: Run Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov

      - name: List installed packages
        run: pip list

      - name: Check working directory
        run: pwd

      - name: Run tests with coverage
        run: |
          PYTHONPATH=./lineardiophantine pytest -v --cov=lineardiophantine --cov-report=xml:coverage.xml --cov-append

      - name: Display coverage.xml
        run: cat coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
